.gitignore
Hi,
Eclipse generates .settings folders with files storing project specific settings. Would be good to filter it using .gitignore.
=> Skip .settings folders generated by Eclipse

core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/AbstractWebLogicWlstStandaloneLocalConfiguration.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic121xWlstInstalledLocalContainer.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic121xWlstStandaloneLocalConfiguration.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic9x10x103x12xWlstOfflineInstalledLocalDeployer.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogicFactoryRegistry.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/WebLogic9x10x103x12xDataSourceConfigurationBuilder.java
Hi,
This is my idea of how WLST could be implemented for Cargo Weblogic container. It could be useful to get rid of deprecated weblogic.Admin and mixing different XML config files. It could bring better flexibility for extending configuration with various options and resources.
Tests are missing as this is kind of proof of concept and it could be complicated to test WLST - it uses python scripts which are executed by Weblogic own tool.
What do you think about this?
=> Possible implementation of WLST usage for Weblogic domain creation and modifications

core/api/container/src/main/java/org/codehaus/cargo/container/configuration/entry/Resource.java, core/api/container/src/main/java/org/codehaus/cargo/container/property/ResourceConverter.java, core/api/container/src/main/java/org/codehaus/cargo/container/property/ResourcePropertySet.java, core/api/container/src/test/java/org/codehaus/cargo/container/configuration/entry/ResourceFixture.java, core/api/container/src/test/java/org/codehaus/cargo/container/property/ResourceConverterTest.java
So far it wasn't possible to set resource id which is needed to be provided in some containers:
Property name in Resource class holds information about JNDI name, which is complicated to be used for this because of special characters used in it (like /).
This patch brings possibility to set our own resource id or used one generated from JNDI name - similar implementation as is used now in creating datasource id.
=> Adding Id property for resources to be possible to set resource name

core/api/container/src/main/java/org/codehaus/cargo/container/configuration/builder/ConfigurationEntryType.java, core/api/generic/src/main/java/org/codehaus/cargo/generic/AbstractFactoryRegistry.java, core/api/generic/src/main/java/org/codehaus/cargo/generic/configuration/builder/ConfigurationBuilderFactory.java, core/api/generic/src/main/java/org/codehaus/cargo/generic/configuration/builder/DefaultConfigurationBuilderFactory.java, core/api/generic/src/test/java/org/codehaus/cargo/generic/TestFactoryRegistry.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/AbstractWebLogicWlstStandaloneLocalConfiguration.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic121xWlstStandaloneLocalConfiguration.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogicFactoryRegistry.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/WebLogic9x10x103x12xWlstStandaloneLocalConfigurationCapability.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/configuration/AbstractWebLogicJmsConfigurationBuilder.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/configuration/WebLogic9x10x103x12xDataSourceConfigurationBuilder.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/configuration/WebLogic9x10x103x12xJmsConnectionFactoryConfigurationBuilder.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/configuration/WebLogic9x10x103x12xJmsQueueConfigurationBuilder.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/configuration/WebLogic9x10x103x12xJmsServerConfigurationBuilder.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/configuration/WebLogic9x10x103x12xJmsSubdeploymentConfigurationBuilder.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/configuration/WebLogic9x10x103x12xJmsSystemResourceConfigurationBuilder.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/configuration/WeblogicConfigurationEntryType.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/configuration/util/PriorityComparator.java, core/containers/weblogic/src/test/java/org/codehaus/cargo/container/weblogic/WebLogic121xWlstStandaloneLocalConfigurationTest.java
Hello,
This is my idea of how Weblogic resource configuration implementation could look. It is implemented by using dedicated configuration builder for every resource supported - so far just JMS - which is bound to specific resource in WebLogicFactoryRegistry.
Some resources have to be created before others, so they are sorted first.
What do you think about this?
=> Adding JMS Resource support for Weblogic container

core/api/container/src/main/java/org/codehaus/cargo/container/ScriptingCapableContainer.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/AbstractWebLogicWlstStandaloneLocalConfiguration.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic121xWlstInstalledLocalContainer.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic121xWlstStandaloneLocalConfiguration.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic9x10x103x12xWlstOfflineInstalledLocalDeployer.java, core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/WebLogicLocalScriptingContainer.java
Implementation of [1].
Introduces interface ScriptingCapableContainer which could be implemented by containers which want to support scripting functionality.
Btw. if you want to keep commits in branch straight - without those Merge pull request commits - this article can be interesting: http://blog.differential.com/best-way-to-merge-a-github-pull-request/
Otherwise Petr Siroky(psiroky) might know how to do it.
[1] https://codehaus-cargo.atlassian.net/browse/CARGO-1321
=> CARGO-1321 - Loose coupling between WebLogic121xWlstInstalledLocalContainer and WebLogic121xWlstStandaloneLocalConfiguration

core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/Tomcat7xStandaloneLocalConfiguration.java, core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/TomcatPropertySet.java, core/containers/tomcat/src/test/java/org/codehaus/cargo/container/tomcat/Tomcat7xStandaloneLocalConfigurationTest.java
Since servlet 3.0 it's possible to expose some web resource throught jars.
After testing I have see that it was not possible throught cargo with Tomcat.
This commit add support for it. It just set the required attribute "addWebinfClassesResources" to true.
More information on tomcat configuration  :
https://tomcat.apache.org/tomcat-7.0-doc/config/context.html
=>  Add support for webjars

core/containers/wildfly/src/main/resources/org/codehaus/cargo/container/internal/resources/wildfly-9/cli/domain/system-property.cli
If system property is already defined in WildFly profile then replace it.
=> CARGO-1408: replace redefined system properties on WildFly

core/containers/wildfly/src/main/java/org/codehaus/cargo/container/wildfly/internal/AbstractWildFlyInstalledLocalContainer.java, core/containers/wildfly/src/main/java/org/codehaus/cargo/container/wildfly/internal/configuration/commands/wildfly8/server/ConnectToServerScriptCommand.java, core/containers/wildfly/src/main/java/org/codehaus/cargo/container/wildfly/internal/configuration/factory/WildFly8xCliConfigurationFactory.java, core/containers/wildfly/src/main/java/org/codehaus/cargo/container/wildfly/internal/configuration/factory/WildFlyCliConfigurationFactory.java, core/containers/wildfly/src/main/resources/org/codehaus/cargo/container/internal/resources/wildfly-8/cli/server/connect-to-server.cli
If CLI script is executed offline or online is controlled now
directly from that CLI script - using command "connect" for eventual
connection to running WildFly instance.
=> CARGO-1417 - refactor server connection for CLI scripts

core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/internal/TomcatManager.java
- remove expect/continue header for PUT requests
- set chunked transfer to use a sensible chunk size
=> CARGO-1418: Tomcat deploy transfer speed

extensions/maven2/plugin/src/main/java/org/codehaus/cargo/maven2/AbstractCargoMojo.java, extensions/maven2/plugin/src/main/java/org/codehaus/cargo/maven2/configuration/Container.java, pom.xml
Implement support for ignoreFailures on all mojos so that maven can still progress through on integration tests with more than one container domain started - also, allow for the specification of a container unique id so that it becomes possible to start more than one container in a pre-integration-test phase and stop more than one container in a post-integration-test phase
=> ignoreFailures and more than one container instance started from maven 

core/api/container/src/main/java/org/codehaus/cargo/container/internal/util/JdkUtils.java, core/api/container/src/test/java/org/codehaus/cargo/container/internal/util/JdkUtilsTest.java
Supports parsing when AbstractInstalledLocalContainer.createJvmLauncher()
tries to parse the following "java -version" output:
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
Fixes:
Caused by: java.lang.NumberFormatException: For input string: "9""
at org.codehaus.cargo.container.internal.util.JdkUtils.parseMajorJavaVersion(JdkUtils.java:138)
at org.codehaus.cargo.container.spi.AbstractInstalledLocalContainer.createJvmLauncher(AbstractInstalledLocalContainer.java:399)
at org.codehaus.cargo.container.spi.AbstractInstalledLocalContainer.startInternal(AbstractInstalledLocalContainer.java:287)
at org.codehaus.cargo.container.spi.AbstractLocalContainer.start(AbstractLocalContainer.java:226)
=> CARGO-1441 Support parsing Java 9 version in JdkUtils

core/containers/pom.xml, core/containers/wildfly-swarm/pom.xml, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/WildFlySwarm2017xInstalledLocalContainer.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/WildFlySwarmFactoryRegistry.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/WildFlySwarmPropertySet.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/WildFlySwarmStandaloneLocalConfiguration.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/AbstractWildFlySwarmInstalledLocalContainer.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/WildFlySwarmContainerCapability.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/WildFlySwarmStandaloneLocalConfigurationCapability.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/WildFlySwarmStartupMonitor.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/configuration/AbstractConfigurator.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/configuration/ConfigurationContext.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/configuration/UserAccountsConfigurator.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/configuration/WildFlySwarmConfiguratorFactory.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/configuration/util/WildFlySwarmUserUtils.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/configuration/yaml/UserAccountsYamlConfigurator.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/configuration/yaml/WildFlySwarmYamlConfiguratorFactory.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/jvm/StackTraceUtil.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/jvm/StreamRedirector.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/jvm/SwarmJvmLauncher.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/jvm/SwarmJvmLauncherFactory.java, core/containers/wildfly-swarm/src/main/resources/META-INF/services/org.codehaus.cargo.generic.AbstractFactoryRegistry, core/containers/wildfly-swarm/src/test/java/org/codehaus/cargo/container/wildfly/swarm/internal/configuration/yaml/YamlGeneratorTest.java, extensions/maven2/samples/pom.xml, extensions/maven2/samples/wildfly-swarm-test/pom.xml, extensions/maven2/samples/wildfly-swarm-test/src/main/java/org/codehaus/cargo/sample/maven2/wildfly/swarm/TestServlet.java, extensions/maven2/samples/wildfly-swarm-test/src/test/java/org/codehaus/cargo/sample/maven2/wildfly/swarm/WildFlySwarmIT.java, pom.xml
Adds support for WildFly Swarm in a new module in core/containers. 
As the container and application are bundled together, this container does not support any deployment. 
Configuration is done via YAML project descriptor passed as an argument when running the swarm uberjar. 
New JVM launcher inspired by DaemonJvmLauncher is required as WildFly Swarm, in contrast to WildFly, cannot rely on management interface, as it's availability depends on user's configuration.
=> CARGO-1440: Add support for WildFly Swarm

core/containers/wildfly-swarm/pom.xml, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/WildFlySwarmFactoryRegistry.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/WildFlySwarmPropertySet.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/AbstractWildFlySwarmInstalledLocalContainer.java, core/containers/wildfly-swarm/src/main/java/org/codehaus/cargo/container/wildfly/swarm/internal/WildFlySwarmStandaloneLocalConfigurationCapability.java, core/samples/java/src/test/java/org/codehaus/cargo/sample/java/AbstractCargoTestCase.java, core/samples/java/src/test/java/org/codehaus/cargo/sample/java/AllLocalContainerTest.java, core/samples/pom.xml
Introducing Hollow Swarm mode as discussed in https://github.com/codehaus-cargo/cargo/pull/94.
- deployments can be added before WildFly Swarm starts
- AllLocalContainerTest is now passing
Tests with deployments are still not working (if e.g. WAR archive is enabled in ContainerCapability); will require further test refactoring. E.g. application context URL is by default root context for swarm, which needs to be changed by placing jboss-deployment-structure.xml descriptor into each test application to make passing.
Feel free to leave this PR open if you want to have the deployment tests addressed as a part of it.
=> Introduce Hollow Swarm mode for WildFly Swarm

core/api/container/src/main/java/org/codehaus/cargo/container/internal/util/JdkUtils.java, core/api/container/src/test/java/org/codehaus/cargo/container/internal/util/JdkUtilsTest.java
Supports parsing when AbstractInstalledLocalContainer.createJvmLauncher()
tries to parse the following "java -version" output:
```
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
```
Fixes:
```
Caused by: java.lang.NumberFormatException: For input string: "10 2018"
at org.codehaus.cargo.container.internal.util.JdkUtils.parseMajorJavaVersion(JdkUtils.java:138)
at org.codehaus.cargo.container.spi.AbstractInstalledLocalContainer.createJvmLauncher(AbstractInstalledLocalContainer.java:399)
at org.codehaus.cargo.container.spi.AbstractInstalledLocalContainer.startInternal(AbstractInstalledLocalContainer.java:287)
at org.codehaus.cargo.container.spi.AbstractLocalContainer.start(AbstractLocalContainer.j …
```
=> CARGO-1457 Support parsing Java 10 version in JdkUtils

core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/Tomcat5xStandaloneLocalConfiguration.java, core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/TomcatPropertySet.java, core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/internal/Tomcat5x6xStandaloneLocalConfigurationCapability.java
In cases when JWTs are stored as cookies, or large Kerberos tokens are being transmitted over the network, having control over the maxHttpHeaderSize setting can make all the difference between failed and successful tests. The below changes should add support for the maxHttpHeaderSize setting, which appears to be supported across Tomcat 4.x-9.x.
=> Add support for Tomcat's maxHttpHeaderSize setting

core/api/container/src/main/java/org/codehaus/cargo/container/spi/startup/CombinedContainerMonitor.java, core/containers/wildfly/src/main/java/org/codehaus/cargo/container/wildfly/internal/AbstractWildFlyInstalledLocalContainer.java, core/containers/wildfly/src/main/java/org/codehaus/cargo/container/wildfly/internal/CLIWildFlyMonitor.java
Wildfly starts management interface too early: when server is not yet fully booted management interface is already reachable in terms of tcp connectivity. The idea is to ping wildfly via CLI API to determine whether it is fully booted or not:
```
~$ java -jar jboss-modules.jar -mp modules org.jboss.as.cli --file=connect.cli
INFO  [org.jboss.modules] JBoss Modules version 1.5.2.Final
INFO  [org.xnio] XNIO version 3.4.0.Final
INFO  [org.xnio.nio] XNIO NIO Implementation Version 3.4.0.Final
INFO  [org.jboss.remoting] JBoss Remoting version 4.0.21.Final
ERROR [org.jboss.as.cli.CommandContext] Timeout waiting for the system to boot.
Timeout waiting for the system to boot.
~$ echo $?
1
~$ 
```
=> Using more advanced technique to test wildfly availability

core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/Tomcat8xStandaloneLocalConfiguration.java, core/samples/java/src/test/java/org/codehaus/cargo/sample/java/tomcat/WarExtraClasspathWithContextTest.java, core/samples/pom.xml, pom.xml, resources/testdata/pom.xml, resources/testdata/tomcat-context-link-simple-jar/pom.xml, resources/testdata/tomcat-context-link-simple-jar/src/main/java/org/codehaus/cargo/sample/testdata/tomcatcontext/TestServlet.java, resources/testdata/tomcat-context-link-simple-jar/src/main/webapp/META-INF/context.xml, resources/testdata/tomcat-context-link-simple-jar/src/main/webapp/WEB-INF/web.xml
Hi, this PR intend to fix https://codehaus-cargo.atlassian.net/projects/CARGO/issues/CARGO-1453, and like I said in the last comment, fix the actual bug in Tomcat8xStandaloneLocalConfiguration#configureExtraClasspathToken because the wrong xml tag if added if the tag "Resources" is not present in context.xml file. I think an additionnal test will be great to detect this error.
=> CARGO-1453: Improve Loading of Jar in Tomcat when Using Resources Mecanism

extensions/daemon/webapp/src/main/java/org/codehaus/cargo/daemon/CargoDaemonServlet.java, extensions/daemon/webapp/src/main/webapp/index.html
I use cargo daemon with windows and internet explorer.
I have issues with cargo daemon and IE. IE show index page and viewlog as XML, not as HTML.
I juste change doctype to HTML5, and it seems working on IE and Chrome.
=> Doctype HTML5

core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/Tomcat8xStandaloneLocalConfiguration.java
Simple fix, our project was crashing with an NPE here, worked up until 1.4.18.
=> Add null check in Tomcat8xStandaloneLocalConfiguration, fix regression introduced in 1.4.19

core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/WebLogicWlstRuntimeConfigurationCapability.java, core/containers/weblogic/src/main/resources/org/codehaus/cargo/container/internal/resources/weblogicWlst/deployment/deploy-deployable-online.py
Users will be able to select the servers destination of the deployment.
=> Enable option "cargo.weblogic.server" for remote deployments on WebLogic.

core/api/module/src/main/resources/org/codehaus/cargo/module/internal/resource/application_1_2.dtd, core/api/module/src/main/resources/org/codehaus/cargo/module/internal/resource/application_1_3.dtd, core/api/module/src/main/resources/org/codehaus/cargo/module/internal/resource/ejb-jar_2_0.dtd, core/api/module/src/main/resources/org/codehaus/cargo/module/internal/resource/web-app_2_2.dtd, core/api/module/src/main/resources/org/codehaus/cargo/module/internal/resource/web-app_2_3.dtd, core/api/module/src/main/resources/org/codehaus/cargo/module/internal/resource/web-app_2_4.xsd, core/api/module/src/main/resources/org/codehaus/cargo/module/internal/resource/web-app_2_5.xsd, core/api/module/src/main/resources/org/codehaus/cargo/module/internal/resource/web-app_3_0.xsd, core/api/util/src/test/resources/jboss-standalone.xml
DTDs taken from https://github.com/eclipse-ee4j/glassfish/tree/master/appserver/deployment/dtds/src/main/resources/glassfish/lib/dtds
XSDs taken from https://github.com/eclipse-ee4j/glassfish/tree/master/appserver/deployment/schemas/src/main/resources/glassfish/lib/schemas
Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>
=> CARGO-1486: Refresh deployment descriptors to have updated license

core/samples/pom.xml, core/uberjar/pom.xml, core/uberjar/src/main/assembly/assembly-src.xml
after this change, if testing on JOnAs and using cargo-core-uberjar then dependency on jonas artifact must be explicitly added by the user to the pom
Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>
=> CARGO-1489: Incorrect license of cargo-core-uberjar

core/containers/jboss/src/main/java/org/codehaus/cargo/container/jboss/JBoss72xInstalledLocalContainer.java
Hi there,
* the JAXP provider is not used if the app argument is missing 
* this makes our deployment fail
* when starting a vanilla JBoss EAP (v. 6.1.0) this app argument is present
Cheers,
Tassilo
=> Add jaxpmodule app argument to jboss72x

core/api/container/src/main/java/org/codehaus/cargo/container/internal/util/ResourceUtils.java
Using Ant 1.10.* yields to NoSuchMethodError: o.a.t.ant.filters.util.ChainReaderHelper.getAssembledReader()Ljava/io/Reader;
=> Fix CARGO-1482: Ant 1.10version incompatibility

core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/TomcatRuntimeConfiguration.java, core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/internal/AbstractTomcatManagerDeployer.java, core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/internal/TomcatManager.java, core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/internal/TomcatRuntimeConfigurationCapability.java
Such "operation" can be: list, undeploy, deploy etc.
This commit CHANGES current behavior, which is to wait FOREVER,
and sets the default timeout to TWO HOURS - because
"you should never ever wait forever"
Two hours was picked to cover "uploading" 500 MB file
over the 1000 Kbps network.
Connect timeout refers to the time to establish the initial connection,
before the start of sending/receiving bytes.
Read timeout refers to the duration between received/send bytes, so:
1. time to first byte
2. time between first and second byte
3. time between second and third byte and so on.
=> Ability to specify timeout for "operation" with runtime Tomcat

extensions/maven2/archetypes/remote-deployment/src/main/resources/archetype-resources/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
=> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/internal/Tomcat7xStandaloneLocalConfigurationCapability.java
* The Tomcat7xStandaloneLocalConfigurationCapability extended the Tomcat5x capability, and was missing the property added for Tomcat6x
=> Document that Tomcat protocol class is supported for Tomcat 7 and up

core/api/container/src/main/java/org/codehaus/cargo/container/installer/Proxy.java, core/api/container/src/main/java/org/codehaus/cargo/container/installer/ZipURLInstaller.java, core/api/container/src/test/java/org/codehaus/cargo/container/installer/ZipURLInstallerTest.java, pom.xml
Pull request to resolve the issue described here: https://groups.google.com/forum/#!topic/codehaus-cargo/81SzGigBjmQ
When downloading a ZIP, the accept header does not include the ZIP mimetype and some web servers may reject this with an HTTP 406. I've set the accept header to a wildcard.
=> Added wildcard accept header

extensions/ant/samples/configurationFiles-xmlReplacements-test/pom.xml, extensions/ant/samples/daemon-test/pom.xml, extensions/ant/samples/datasource-test/pom.xml, extensions/ant/samples/remote-test/pom.xml, extensions/ant/samples/users-test/pom.xml
* Without this properly configured, mvn install -DskipTests falls over with errors in each samples directory
=> Skip copying dependencies and running ant when skipTests is true

core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/Tomcat5xStandaloneLocalConfiguration.java, core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/Tomcat6xStandaloneLocalConfiguration.java, core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/Tomcat7xStandaloneLocalConfiguration.java, core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/Tomcat8xStandaloneLocalConfiguration.java, core/containers/tomcat/src/test/java/org/codehaus/cargo/container/tomcat/Tomcat6xStandaloneLocalConfigurationTest.java, core/containers/tomcat/src/test/java/org/codehaus/cargo/container/tomcat/Tomcat8xStandaloneLocalConfigurationTest.java
* The old implementation assumed that only a handful of different protocol classes would be used. It didn't support Nio2 or Apr protocol classes, and would break if some other custom protocol class was used too
* This implementation uses a different connector xpath expression based on the value of the custom connector protocol class property. If it's not set, then the old selector is still used.
* Verified that interactions with the customized connector protocol still work, so that things like HTTP/2 upgrade are guaranteed to be configured correctly when Nio2 or Apr classes are used
=> Support customizing the tomcat connector protocol with more classes

core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/Tomcat5xStandaloneLocalConfiguration.java, core/containers/tomcat/src/test/java/org/codehaus/cargo/container/tomcat/Tomcat6xStandaloneLocalConfigurationTest.java
* Now working for all SSL configuration properties supported from Tomcat5x and up
=> Further fixes for custom connector protocols

core/containers/glassfish/src/main/java/org/codehaus/cargo/container/glassfish/GlassFish3xInstalledLocalDeployer.java
according to [the documentation](https://codehaus-cargo.github.io/cargo/Maven2+Plugin+Reference+Guide.html#Maven2PluginReferenceGuide-prop2) deployables of type `EAR` supposed to support the `<name>` property. That doesn't seem to work for glassfish/payara. Here is the fix for that
=> [payara] support deployable EAR name property

extensions/maven3/plugin/src/main/java/org/codehaus/cargo/maven3/AbstractCargoMojo.java, extensions/maven3/plugin/src/main/java/org/codehaus/cargo/maven3/log/MavenLogger.java
Added parameter to maven plugin to allow the user to disable category  log prefix, because sometimes this prefix consume too much space in console and/or make messages less readable.
=> Added parameter 'cargo.maven.useLogCategoryPrefix' to maven plugin

core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/Tomcat8xStandaloneLocalConfiguration.java, core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/TomcatPropertySet.java
Use case : Chapter Ordering in https://tomcat.apache.org/tomcat-8.0-doc/config/resources.html
`Since both resources are PostResources, it might be expected that D:\Projects\external\classes will be searched for classes before D:\Projects\lib\library1.jar. However, by adding the JAR using a FileResourceSet, the JAR is mapped to /WEB-INF/lib and will be processed at application start along with the other JARs in /WEB-INF/lib. The classes from the JAR file will be added to the ClassResources which means they will be searched before the classes from D:\Projects\external\classes. If the desired behaviour is that D:\Projects\external\classes is searched before D:\Projects\lib\library1.jar then a slightly different configuration is required:
<Resources>
<PostResources …
=> Property to tell to Tomcat to map JARs in WEB-INF/lib or WEB-INF/classes
