- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/AbstractWebLogicWlstStandaloneLocalConfiguration.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic121xWlstInstalledLocalContainer.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic121xWlstStandaloneLocalConfiguration.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic9x10x103x12xWlstOfflineInstalledLocalDeployer.java
Adding log entries for WLST changes.
WLST modifications are triggered for datasources and resources just in case there are some to create.
> Adding logging information for Weblogic domain changes.

- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/WebLogic9x10x103x12xWlstStandaloneLocalConfigurationCapability.java
As it is possible to do it now with WLST.
> Added support for setting admin username and password.

- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/AbstractWebLogicWlstStandaloneLocalConfiguration.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic121xWlstStandaloneLocalConfiguration.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogicPropertySet.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/configuration/rules/WeblogicResourceRules.java
- core/containers/weblogic/src/test/java/org/codehaus/cargo/container/weblogic/internal/configuration/rules/WeblogicResourceRulesTest.java
Added functionality for Weblogic to automatically add resources which are mandatory for creating JMS connection factory or queue.
> Support for adding needed Weblogic JMS resources if they aren't defined in properties.

- core/api/module/src/main/java/org/codehaus/cargo/module/XmlEntityResolver.java
- core/api/module/src/main/resources/org/codehaus/cargo/module/internal/resource/jboss-web_5_0.dtd
- core/api/module/src/main/resources/org/codehaus/cargo/module/internal/resource/jboss_5_0.dtd
- core/api/module/src/main/resources/org/codehaus/cargo/module/internal/resource/service-ref_5_0.dtd
Fix for https://codehaus-cargo.atlassian.net/browse/CARGO-1322
> CARGO-1322 -  JBoss 5 DTDs added

- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/AbstractWebLogicWlstStandaloneLocalConfiguration.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic121xWlstStandaloneLocalConfiguration.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic9x10x103x12xWlstOfflineInstalledLocalDeployer.java
Fixed by setting raw format of WLST command.
> CARGO-1323 - WLST domain handling on Windows fix

- core/api/container/src/main/java/org/codehaus/cargo/container/property/User.java
Fixed by checking that usersAsString contains non null value.
> CARGO-1326 - NullPointerException when skipped <cargo.servlet.users> tag

- core/api/container/src/main/java/org/codehaus/cargo/container/ScriptingCapableContainer.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic121xWlstInstalledLocalContainer.java
First part of CARGO-1331 implementation.
> CARGO-1331 - added WebLogic container support for processing WLST script files

- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic121xWlstInstalledLocalContainer.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic121xWlstStandaloneLocalConfiguration.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/AbstractWebLogicWlstStandaloneLocalConfiguration.java
- core/containers/weblogic/src/test/java/org/codehaus/cargo/container/weblogic/internal/AbstractWebLogicWlstStandaloneLocalConfigurationTest.java
Also moved AbstractWebLogicWlstStandaloneLocalConfiguration to keep source code structure clean.
> CARGO-1251 - Added WLST implementation for stopping container

- core/api/container/src/main/java/org/codehaus/cargo/container/configuration/StandaloneLocalConfiguration.java
- core/api/container/src/main/java/org/codehaus/cargo/container/spi/configuration/AbstractStandaloneLocalConfiguration.java
- core/api/container/src/test/java/org/codehaus/cargo/container/stub/StandaloneLocalConfigurationStub.java
- core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/Tomcat5xStandaloneLocalConfiguration.java
> Fix for CARGO-1350

- core/api/container/src/main/java/org/codehaus/cargo/container/property/GeneralPropertySet.java
- core/api/container/src/main/java/org/codehaus/cargo/container/spi/AbstractInstalledLocalContainer.java
- core/api/container/src/main/java/org/codehaus/cargo/container/spi/configuration/AbstractStandaloneLocalConfigurationCapability.java
useful for remote debug and JMX access
> added support for start-only JVM arguments

- core/containers/websphere/src/main/java/org/codehaus/cargo/container/websphere/WebSphere85xStandaloneLocalConfiguration.java
- core/containers/websphere/src/main/java/org/codehaus/cargo/container/websphere/WebSpherePropertySet.java
- core/containers/websphere/src/main/java/org/codehaus/cargo/container/websphere/internal/WebSphere85xStandaloneLocalConfigurationCapability.java
- core/containers/websphere/src/main/java/org/codehaus/cargo/container/websphere/internal/configuration/WebSphereJythonConfigurationFactory.java
- core/containers/websphere/src/main/java/org/codehaus/cargo/container/websphere/internal/configuration/commands/deployment/DeployDeployableScriptCommand.java
- core/containers/websphere/src/main/java/org/codehaus/cargo/container/websphere/internal/configuration/commands/domain/SetGlobalSecurityPropertyScriptCommand.java
- core/containers/websphere/src/main/java/org/codehaus/cargo/container/websphere/internal/configuration/commands/domain/SetSessionManagementPropertyScriptCommand.java
- core/containers/websphere/src/main/java/org/codehaus/cargo/container/websphere/util/ComplexPropertyParser.java
- core/containers/websphere/src/main/resources/org/codehaus/cargo/container/internal/resources/websphere85x/commands/domain/set-global-security-property.py
- core/containers/websphere/src/main/resources/org/codehaus/cargo/container/internal/resources/websphere85x/commands/domain/set-session-management-property.py
- core/containers/websphere/src/main/resources/org/codehaus/cargo/container/internal/resources/websphere85x/commands/resource/datasource-connection-property.py
- core/containers/websphere/src/main/resources/org/codehaus/cargo/container/internal/resources/websphere85x/commands/resource/datasource.py
- core/containers/websphere/src/test/java/org/codehaus/cargo/container/websphere/util/ComplexPropertyParserTest.java
Fixed datasource connection property configuration.
Small refactoring.
> CARGO-1351 - configuration extension

- core/api/container/src/main/java/org/codehaus/cargo/container/internal/util/ComplexPropertyUtils.java
- core/api/container/src/test/java/org/codehaus/cargo/container/internal/util/ComplexPropertyUtilsTest.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic121xInstalledLocalContainer.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic121xStandaloneLocalConfiguration.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogicPropertySet.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/WebLogicWlstStandaloneLocalConfigurationCapability.java
- core/containers/websphere/src/main/java/org/codehaus/cargo/container/websphere/WebSphere85xExistingLocalConfiguration.java
- core/containers/websphere/src/main/java/org/codehaus/cargo/container/websphere/WebSphere85xInstalledLocalContainer.java
- core/containers/websphere/src/main/java/org/codehaus/cargo/container/websphere/WebSphere85xStandaloneLocalConfiguration.java
- core/containers/websphere/src/main/java/org/codehaus/cargo/container/websphere/WebSpherePropertySet.java
- core/containers/websphere/src/main/java/org/codehaus/cargo/container/websphere/internal/WebSphere85xStandaloneLocalConfigurationCapability.java
- core/containers/websphere/src/main/java/org/codehaus/cargo/container/websphere/internal/configuration/commands/deployment/DeployDeployableScriptCommand.java
WebSphere existing config - added redeploying deployables
> CARGO-1331 - support for external scripts

- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic121xStandaloneLocalConfiguration.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogicPropertySet.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogicWlstOfflineInstalledLocalDeployer.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/WebLogicWlstStandaloneLocalConfigurationCapability.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/configuration/WebLogicWlstConfigurationFactory.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/configuration/commands/deployment/DeployDeployableScriptCommand.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/internal/configuration/commands/domain/SslScriptCommand.java
- core/containers/weblogic/src/main/resources/org/codehaus/cargo/container/internal/resources/weblogicWlst/domain/create-domain.py
- core/containers/weblogic/src/main/resources/org/codehaus/cargo/container/internal/resources/weblogicWlst/domain/ssl.py
- core/documentation/src/main/java/org/codehaus/cargo/documentation/ConfluenceContainerDocumentationGenerator.java
Separated WLST deployer from standalone configuration, small deployer refactoring.
> CARGO-1362 - WebLogic: added SSL and logging configuration

- core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/Tomcat8xStandaloneLocalConfiguration.java
Classes defined before libs, are not loading before libs
Directory declared contains many jars
See : https://codehaus-cargo.atlassian.net/browse/CARGO-1367
> CARGO-1367 : fix 2 possibles bugs with tomcat 8 Resources

- README.md
Makes it much easier to find and access the JIRA.
> Add JIRA link to the README

- core/api/module/src/main/java/org/codehaus/cargo/module/XmlEntityResolver.java
Fix for https://codehaus-cargo.atlassian.net/browse/CARGO-1374
> CARGO-1374 - jboss-web_5_0.dtd identifier fixed

- core/api/container/src/main/java/org/codehaus/cargo/container/property/User.java
- core/api/container/src/test/java/org/codehaus/cargo/container/property/UserTest.java
Also refactored user parsing to become more understandable
> CARGO-1376 - trimming of whitespaces from user name

- core/samples/java/src/test/java/org/codehaus/cargo/sample/java/AbstractWarCapabilityContainerTestCase.java
- core/samples/java/src/test/java/org/codehaus/cargo/sample/java/AllLocalContainerTest.java
- core/samples/java/src/test/java/org/codehaus/cargo/sample/java/EarCapabilityContainerTest.java
- core/samples/java/src/test/java/org/codehaus/cargo/sample/java/RemoteDeploymentTest.java
- pom.xml
Allows us to use Assume functionality which properly indicates tests as skipped if condition isn't met.
> Raised JUnit version

- core/api/util/src/main/java/org/codehaus/cargo/util/DefaultXmlFileBuilder.java
- core/api/util/src/main/java/org/codehaus/cargo/util/NamespaceContextImpl.java
- core/api/util/src/main/java/org/codehaus/cargo/util/XmlUtils.java
- core/api/util/src/test/java/org/codehaus/cargo/util/XmlUtilsTest.java
- core/containers/jboss/src/main/java/org/codehaus/cargo/container/jboss/JBoss75xStandaloneLocalConfiguration.java
Needed for JBoss75x for mail resource.
> Implement namespace awareness in XmlUtils

- core/containers/glassfish/src/main/java/org/codehaus/cargo/container/glassfish/GlassFish3xInstalledLocalDeployer.java
This patch enables proper custom Resource creation on Glassfish 3.
I don't have a local Glassfish to run tests but style issues were fixed now.
> fix checkstyle violations

- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic103xRemoteContainer.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogic103xRuntimeConfiguration.java
- core/containers/weblogic/src/main/java/org/codehaus/cargo/container/weblogic/WebLogicFactoryRegistry.java
feature request: https://groups.google.com/forum/#!topic/codehaus-cargo/n3PmeaRN1P8
> weblogic 10.3.x remote runtime support

- core/containers/geronimo/src/main/java/org/codehaus/cargo/container/geronimo/internal/GeronimoUtils.java
- core/samples/java/src/main/java/org/codehaus/cargo/sample/java/PingUtils.java
- core/samples/java/src/test/java/org/codehaus/cargo/sample/java/TransactionEmulationDataSourceOnStandaloneConfigurationTest.java
- core/samples/java/src/test/java/org/codehaus/cargo/sample/java/XADatasourceResourceOnStandaloneConfigurationTest.java
- core/samples/java/src/test/java/org/codehaus/cargo/sample/java/XATransactionDataSourceOnStandaloneConfigurationTest.java
- core/samples/java/src/test/java/org/codehaus/cargo/sample/java/XATransactionEmulationDataSourceOnStandaloneConfigurationTest.java
Also fix Geronimo port offset issue.
> Improve sample tests, activate WildFly for datasource tests

- core/api/container/src/main/java/org/codehaus/cargo/container/configuration/LocalConfiguration.java
- core/api/container/src/main/java/org/codehaus/cargo/container/spi/AbstractLocalContainer.java
- core/api/container/src/main/java/org/codehaus/cargo/container/spi/configuration/AbstractLocalConfiguration.java
- core/api/container/src/main/java/org/codehaus/cargo/container/spi/startup/AbstractContainerMonitor.java
- core/api/container/src/main/java/org/codehaus/cargo/container/startup/ContainerMonitor.java
- core/api/container/src/test/java/org/codehaus/cargo/container/spi/configuration/LocalConfigurationTest.java
- core/api/container/src/test/java/org/codehaus/cargo/container/stub/AbstractLocalConfigurationStub.java
- core/containers/wildfly/src/main/java/org/codehaus/cargo/container/wildfly/WildFly8xStandaloneLocalConfiguration.java
- core/containers/wildfly/src/main/java/org/codehaus/cargo/container/wildfly/WildFly9xStandaloneLocalConfiguration.java
- core/containers/wildfly/src/main/java/org/codehaus/cargo/container/wildfly/internal/AbstractWildFlyInstalledLocalContainer.java
- core/containers/wildfly/src/main/java/org/codehaus/cargo/container/wildfly/internal/ManagementUrlWildFlyMonitor.java
Used also to remove need for deploying Cargo CPC war file for WildFly.
> CARGO-268: initial implementation

- core/containers/wildfly/src/main/java/org/codehaus/cargo/container/wildfly/WildFly8xStandaloneLocalConfiguration.java
- core/containers/wildfly/src/main/java/org/codehaus/cargo/container/wildfly/internal/AbstractWildFlyStandaloneLocalConfiguration.java
Newly created modules are dependent on previously defined.
> CARGO-1444: Introduce dependencies to WildFly modules.

- core/api/container/src/test/java/org/codehaus/cargo/container/stub/InstalledLocalContainerStub.java
- extensions/maven2/plugin/src/main/java/org/codehaus/cargo/maven2/configuration/Container.java
- extensions/maven2/plugin/src/test/java/org/codehaus/cargo/maven2/configuration/ContainerTest.java
Test showing the problem + fix for it.
> CARGO-1445: Preserve order of container dependencies

- core/samples/pom.xml
> WildFly 11 Final is released

- core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/TomcatPropertySet.java
- core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/internal/AbstractTomcatManagerDeployer.java
- core/containers/tomcat/src/main/java/org/codehaus/cargo/container/tomcat/internal/TomcatRuntimeConfigurationCapability.java
I would like to send "update" parameter when doing a deploy to Tomcat Manager. The TomcatManager class already supports it, this suggested patch exposes the feature as a configuration option.
> Support Tomcat deploy update

- core/tools/jboss-deployer-5.1-and-6/pom.xml
- core/tools/jboss-deployer-5/pom.xml
* These aren't in central, and are not actually required in tests
> Exclude old sun-jaxb artifacts

- core/containers/websphere/src/main/java/org/codehaus/cargo/container/websphere/WebSphere85xInstalledLocalContainer.java
Signed-off-by: Karel Suta <ksuta@redhat.com>
> CARGO-1548: Add a space between script name and its arguments
